### ISSUE TITLE
Unimplemented code being hit on some il2cpp methods

### ISSUE THREAD

**Issue by RinLovesYou** [BepInEx/Dobby#1]
Some methods (even on x64 games) hit this unimplemented code in dobby. An issue about this has been raised upstream back in April, but doesn't seem to have gotten any sort of attention yet

Maybe you could take a look at implementing this

```
[!][/tmp/Dobby/source/InstructionRelocation/x86/x86_insn_decode/x86_insn_decode.c:454:x86_insn_decode_opcode]: 
[!] unimplemented code!!!

[1]    946388 abort (core dumped)
```

**Comment by Kasuromi** [comment]
I've added *partial* support for SSE instructions over at the [`sse-impl`](https://github.com/BepInEx/Dobby/tree/sse-impl) branch.

I tested it with simple routines that start with movss/movups instructions, but not the other SSE instructions. Check out the build artifacts and let me know if you run into any issues.

**Comment by RinLovesYou** [comment]
Yep that seems to work, thanks a bunch!
