### ISSUE TITLE
undefined reference to "DobbyInstrument"

### ISSUE THREAD

**Issue by Taardisaa** [BepInEx/Dobby#4]
I tried to write a sample code for the function `DobbyInstrument` but got a compilation error.
Then I looked into libdobby_x64.so and libdobby_x86.so for Linux and can't find the export function `DobbyInstrument ` yet it exists in the header file `dobby.h`.

**Comment by Kasuromi** [comment]
The `DobbyInstrument` function is only compiled and exported when compiling with the `DynamicBinaryInstrument` flag which isn't enabled for our distribution builds. Have you tried compiling it locally with the compiler flag enabled?

**Comment by Taardisaa** [comment]
> The `DobbyInstrument` function is only compiled and exported when compiling with the `DynamicBinaryInstrument` flag which isn't enabled for our distribution builds. Have you tried compiling it locally with the compiler flag enabled?

No, I just tried the distribution build for convenience. Thank you for your inform and I will try to compile it myself, but maybe you can also mention this on the Release page?
